config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/users/:id', to: 'pages#profile', as: :user_profile
  get '/status/:id', to: 'pages#status', as: :loan_status

  get '/accepted/:id', to: 'loan_proposals#accept', as: :accept_loan

  resources :users do
    resources :addresses do
    end
  end
  resources :loan_proposals do
  end
  resources :score_data do
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/culture.rb
class Culture < ApplicationRecord
  belongs_to :user
end

app/models/loan_accepted.rb
class LoanAccepted < ApplicationRecord
  belongs_to :user
  belongs_to :loan_proposal
end

app/models/loan_proposal.rb
class LoanProposal < ApplicationRecord
  belongs_to :user
end

app/models/scoredatum.rb
class Scoredatum < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :loan_proposals
  has_many :loan_accepteds, through: :loan_proposals
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  def index
    @addresses = Address.all
  end

  def new
    @address = Address.new
    @user = current_user
    authorize @address
  end

  def create
    @address = Address.new(address_params)
    authorize @address
    @address.user = current_user
    if @address.save!
      redirect_to user_profile_path(current_user)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

private

  def set_address
    @address = Address.find(params[:id])
  end

  def address_params
    params.require(:address).permit(:city, :street, :number, :neighborhood, :cep)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :except => [:home]
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Devise Redirect after sign to profile page
  def after_sign_in_path_for(resource)
    user_profile_path(current_user.id)
  end

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/cultures_controller.rb
class CulturesController < ApplicationController
end

app/controllers/loan_accepteds_controller.rb
class LoanAcceptedsController < ApplicationController
end

app/controllers/loan_proposals_controller.rb
class LoanProposalsController < ApplicationController
  before_action :set_loan_proposal, only: [:show, :edit, :update, :destroy]

  def new
    @loan_proposal = LoanProposal.new
    authorize @loan_proposal
  end

  def create
    @loan_proposal = LoanProposal.new(loan_proposal_params)
    @loan_proposal.user = current_user
    @loan_proposal.accepted = "Enviado"
    if @loan_proposal.save
      redirect_to loan_proposal_path(@loan_proposal), notice: "Proposta de empréstimo realizada com sucesso"
    else
      render :new
    end
    authorize @loan_proposal
  end

  def accept
    @loan_proposal = LoanProposal.find(params[:id])
    @loan_proposal.accepted = 'Aceito'
    @loan_proposal.save
    redirect_to user_profile_path, notice: "Proposta aceita com sucesso!"
    authorize @loan_proposal
  end

  def index
    @loan_proposals = policy_scope(LoanProposal)
  end

  def show
    authorize @loan_proposal
  end

  def edit
  end

  def update
    @loan_proposal.update(loan_proposal_params)
    redirect_to loan_proposal_path(@loan_proposal)
    authorize @loan_proposal
  end

  def destroy
  end

  private

  def set_loan_proposal
    @loan_proposal = LoanProposal.find(params[:id])
  end

  def loan_proposal_params
    params.require(:loan_proposal).permit(:conditions, :amount, :accepted, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def profile
    @user = current_user
    @address = Address.new
    @loan_proposals = LoanProposal.all
  end
 #comentario
end

app/controllers/scoredatas_controller.rb
class ScoredatasController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= simple_form_for [@user,@address] do |f| %>
  <%= f.input :city %>
  <%= f.input :street %>
  <%= f.input :number %>
  <%= f.input :neighborhood %>
  <%= f.input :cep %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agrocashpundit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/loan_proposals/new.html.erb
<h1>Proposta de empréstimo</h1>
<%= simple_form_for [@loan_proposal] do |f| %>
  <%= f.input :amount %>
  <%= f.input :conditions, :collection => ["12x", "24x", "48x"] %>
  <%= f.input :description %>
  <%= f.submit %>
<% end %>

app/views/loan_proposals/show.html.erb
<div class="container pt-5 mt-5">
  <h1>Proposta de empréstimo</h1>
    <div class= "row">
      <div class="col-lg-8 pt-6">
        <h5 class="my-3 pt-3"><strong>Valor do montante: <%= @loan_proposal.amount %></strong></h5>
        <h5 class="my-3 pt-3"><strong>Descrição da proposta: <%= @loan_proposal.description %></strong></h5>
        <h5 class="my-3 pt-3"><strong>Status: <%= @loan_proposal.accepted %></strong></h5>
      </div>

        <%= link_to 'Voltar para Home', user_profile_path %>

        <% if current_user.role == 'investor' %>
          <%= link_to 'Aceitar Proposta', accept_loan_path(@loan_proposal) %>
        <% end %>


    </div>
</div>

app/views/pages/_investor.html.erb
<h1>Opções de Investimento</h1>
<% @loan_proposals.each do |proposal| %>
  <p>Email do Usuário: <%= proposal.user.email %></p>
  <p>Valor: <%= proposal.amount %></p>
  <p>Condições: <%= proposal.conditions %></p>
  <%= link_to 'Detalhes', loan_proposal_path(proposal) %>
  <%= link_to 'Detalhes 2', loan_proposal_path(proposal.id) %>
<% end %>

app/views/pages/home.html.erb
<div class="home-banner">
  <h1>Le Wagon</h1>
  <p>
  <span data-controller="typed-js"></span>
</p>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <%= "Lorem ipsum dolor sit amet, consectetur adipisicing elit " * 100 %>
    </div>
  </div>
</div>


<div class="card" style="width: 18rem;">
  <img src="https://images.unsplash.com/photo-1599939571322-792a326991f2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8bmlnaHQlMjBjaXR5fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Hello Bootcampers!!!!!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container mt-5">

  <h1> Profile Page</h1>
    <%= link_to 'New Address', new_user_address_path(current_user.id) %>
    <%= link_to 'Criar pedido de empréstimo', new_loan_proposal_path %>
    <% @loan_proposals.each do |proposal| %>
      <%= link_to 'Detalhes da Proposta', loan_proposal_path(proposal) %>
    <% end  %>
    <% @loan_proposals.each do |proposal| %>
      <p><%= proposal.amount %></p>
      <p><%= proposal.conditions %></p>
      <p><%= proposal.accepted %></p>
      <%= link_to 'Detalhes da Proposta', loan_proposal_path(proposal) %>
    <% end %>
</div>

app/views/pages/status.html.erb
<h1>Status do pedido de empréstimo</h1>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer fixed-bottom">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/TamaraToyota", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>